version: '3.8'
services:
  web:
    image: php:8.4-apache
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/html
    command: |
      bash -c "
      a2enmod rewrite &&
      echo '<Directory /var/www/html>
        AllowOverride All
        Require all granted
      </Directory>' > /etc/apache2/conf-available/allow-htaccess.conf &&
      a2enconf allow-htaccess &&
      apache2-foreground
      "